language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda info -a
  
install:
  - conda env create -q -f environment.yml
  - source .envrc

script:
  - python `which nosetests` -v
