name: reflection
channels:
- anaconda
- anaconda-fusion
- conda-forge
- soumith
- defaults
dependencies:
- matplotlib=2.0.2=np113py35_0
- mkl=2017.0.3=0
- numexpr=2.6.2=np113py35_0
- numpy=1.13.1=py35_0
- pandas=0.20.2=np113py35_0
- pyqt=5.6.0=py35_2
- qt=5.6.2=2
- scikit-learn=0.18.2=np113py35_0
- scipy=0.19.1=np113py35_0
- bleach=1.5.0=py35_0
- boto=2.48.0=py35_0
- bz2file=0.98=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.11=py35_0
- entrypoints=0.2.3=py35_0
- flake8=3.4.1=py35_0
- freetype=2.5.5=2
- gensim=2.3.0=np113py35_0
- html5lib=0.9999999=py35_0
- icu=54.1=0
- ipykernel=4.6.1=py35_0
- ipython=6.1.0=py35_0
- ipython_genutils=0.2.0=py35_0
- isort=4.2.15=py35_0
- jedi=0.10.2=py35_2
- jinja2=2.9.6=py35_0
- jsonschema=2.6.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- libpng=1.6.27=0
- markupsafe=0.23=py35_2
- mistune=0.7.4=py35_0
- mkl-rt=11.1=p0
- mkl-service=1.1.0=py35_p0
- nbconvert=5.2.1=py35_0
- nbformat=4.3.0=py35_0
- nose=1.3.7=py35_0
- notebook=5.0.0=py35_0
- openssl=1.0.2l=0
- pandocfilters=1.4.1=py35_0
- path.py=10.3.1=py35_0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.14=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.2.0=py35_0
- pyparsing=2.1.4=py35_0
- python=3.5.3=1
- python-dateutil=2.6.0=py35_0
- pytorch=0.2.0
- pytz=2017.2=py35_0
- pyzmq=16.0.2=py35_0
- readline=6.2=2
- requests=2.14.2=py35_0
- seaborn=0.8.0=py35_0
- setuptools=36.5.0=py35ha8c1747_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- smart_open=1.5.3=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.18=0
- tornado=4.5.1=py35_0
- tqdm=4.14.0=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- yapf=0.18.0=py_0
- zlib=1.2.8=3
- pip:
  - attrs==17.2.0
  - cython==0.26
  - click==6.7
  - eli5==0.7
  - graphviz==0.8
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - olefile==0.44
  - pillow==4.2.1
  - prompt-toolkit==1.0.14
  - pyformat==0.7
  - pyro-ppl==0.1.2
  - git+https://github.com/NicolasHug/Surprise.git
  - singledispatch==3.4.0.3
  - smart-open==1.5.3
  - tabulate==0.7.7
  - timer==0.1
  - typing==3.6.1
  - wordcloud==1.3.1
